{% set name = "adsorption-file-parser" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adsorption_file_parser-{{ version }}.tar.gz
  sha256: 8510f8019eb3a2278547b71c5de9203721ebf0f9556ac8c8f01e896e57948364

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - openpyxl
    - python-dateutil
    - xlrd >=1.1
    - xlwt >=1.3

test:
  imports:
    - adsorption_file_parser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AIF-development-team/adsorption-file-parser
  summary: Collection of parsers for (nearly) all commercial adsorption instrumentation.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pauliacomi
