{% set name = "adsorption-file-parser" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adsorption_file_parser-{{ version }}.tar.gz
  sha256: 7c8bd02af0a46beccc54090c9abfe7a29963014fd134199500d32ef8ebba2332

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - openpyxl
    - python-dateutil
    - xlrd >=1.1
    - xlwt >=1.3

test:
  imports:
    - adsorption_file_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AIF-development-team/adsorption-file-parser
  summary: Collection of parsers for (nearly) all commercial adsorption instrumentation.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pauliacomi
